import { createApp } from 'vue';
import './bootstrap.js';
import App from './App.vue';
import router from './router';
import vuetify from './plugins/vuetify';
// import DatePicker from '@alireza-ab/vue3-persian-datepicker';
import { createPinia } from 'pinia';
const app = createApp(App);
const pinia = createPinia();
// app.component('DatePicker', DatePicker);
app.use(vuetify);
app.use(pinia);
app.use(router);
app.mount('#app');
